### ISSUE TITLE
Unable to run demo on windows

### ISSUE THREAD

**Issue by 78Alpha** [roatienza/efficientspeech#10]
```
(es) Q:\Utilities\CUDA\efficientspeech>python demo.py --checkpoint https://github.com/roatienza/efficientspeech/releases/download/pytorch2.0.1/tiny_eng_266k.ckpt  --infer-device cpu --text "the quick brown fox jumps over the lazy dog" --wav-filename fox.wav
100%|█████████████████████████████████████████████████████████████████████████████| 6.76M/6.76M [00:00<00:00, 68.4MB/s]
A:\Anaconda\envs\es\lib\site-packages\torch\nn\utils\weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Removing weight norm...
Traceback (most recent call last):
  File "Q:\Utilities\CUDA\efficientspeech\demo.py", line 121, in <module>
    model = model.load_from_checkpoint(checkpoint,
  File "A:\Anaconda\envs\es\lib\site-packages\lightning\pytorch\utilities\model_helpers.py", line 93, in __get__
    raise TypeError(
TypeError: The classmethod `EfficientSpeech.load_from_checkpoint` cannot be called on an instance. Please call it on the class type and make sure the return value is used.
```

**Comment by Nanayeb34** [comment]
@78Alpha . I cam across this issue. It seems to be a bug from the demo.py script. With pytorch lightning, the `load_from_checkpoint` is supposed to be called on the class itself and not an instance of the class. 

Go to line 122 of the demo.py script and replace it with 
`        model = EfficientSpeech.load_from_checkpoint(checkpoint_path=checkpoint,
                                                    infer_device=args.infer_device,
                                                    hifigan_checkpoint=args.hifigan_checkpoint,
                                                    map_location=torch.device('cpu'))`

It should work now.

**Comment by 78Alpha** [comment]
The demo indeed works after this change. Thank you.
